enum Gender {
  MALE
  FEMALE
}

type User {
  _id: ID!
  firstName: String
  lastName: String
  name: String
  email: String
  gender: Gender
  ipAddress: String
}

input UserCandidate {
  firstName: String
  lastName: String
  email: String
  gender: Gender
  ipAddress: String
}

type Query {
  getUsers(lastName: String): [User]!
}

type Mutation {
  createUser(user: UserCandidate!): User!
  updateUser(id: ID!, userUpdate: UserCandidate!): User!
  deleteUser(id: ID!): Boolean!
}

